catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': ^6.7.3
    '@types/estree': ^1.0.8
    '@types/node': ^25.0.3
    '@types/picomatch': ^4.0.2
    '@vitest/coverage-v8': ^4.0.16
    bumpp: ^10.3.2
    chokidar: ^5.0.0
    eslint: ^9.39.2
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vue-tsc: ^3.2.1
  playground:
    '@vitejs/plugin-vue': ^6.0.3
    vite: ^7.3.0
    vite-plugin-inspect: ^11.3.3
    vue: ^3.5.26
  prod:
    acorn: ^8.15.0
    escape-string-regexp: ^5.0.0
    estree-walker: ^3.0.3
    local-pkg: ^1.1.2
    magic-string: ^0.30.21
    mlly: ^1.8.0
    pathe: ^2.0.3
    picomatch: ^4.0.3
    pkg-types: ^2.3.0
    scule: ^1.3.0
    strip-literal: ^3.1.0
    tinyglobby: ^0.2.15
    unplugin: ^2.3.11
    unplugin-utils: ^0.3.1
  test:
    h3: ^1.15.4
    jquery: ^3.7.1
    lit: ^3.3.2
    vitest: ^4.0.16
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
