packages:
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@types/estree': ^1.0.8
    '@types/node': ^24.6.1
    '@types/picomatch': ^4.0.2
    '@vitest/coverage-v8': ^3.2.4
    bumpp: ^10.2.3
    eslint: ^9.36.0
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vue-tsc: ^3.1.0
  playground:
    '@vitejs/plugin-vue': ^6.0.1
    vite: ^7.1.7
    vite-plugin-inspect: ^11.3.3
    vue: ^3.5.22
  prod:
    acorn: ^8.15.0
    escape-string-regexp: ^5.0.0
    estree-walker: ^3.0.3
    local-pkg: ^1.1.2
    magic-string: ^0.30.19
    mlly: ^1.8.0
    pathe: ^2.0.3
    picomatch: ^4.0.3
    pkg-types: ^2.3.0
    scule: ^1.3.0
    strip-literal: ^3.1.0
    tinyglobby: ^0.2.15
    unplugin: ^2.3.10
    unplugin-utils: ^0.3.0
  test:
    h3: ^1.15.4
    jquery: ^3.7.1
    lit: ^3.3.1
    vitest: ^3.2.4
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
