catalogMode: prefer
minimumReleaseAgeExclude:
  - '@devframes/hub@0.7.15'
  - '@devframes/json-render@0.7.15'
  - '@devframes/plugin-inspect@0.7.15'
  - '@devframes/plugin-messages@0.7.15'
  - '@devframes/plugin-terminals@0.7.15'
  - '@rolldown/binding-android-arm64@1.2.1'
  - '@rolldown/binding-darwin-arm64@1.2.1'
  - '@rolldown/binding-darwin-x64@1.2.1'
  - '@rolldown/binding-freebsd-x64@1.2.1'
  - '@rolldown/binding-linux-arm-gnueabihf@1.2.1'
  - '@rolldown/binding-linux-arm64-gnu@1.2.1'
  - '@rolldown/binding-linux-arm64-musl@1.2.1'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.1'
  - '@rolldown/binding-linux-s390x-gnu@1.2.1'
  - '@rolldown/binding-linux-x64-gnu@1.2.1'
  - '@rolldown/binding-linux-x64-musl@1.2.1'
  - '@rolldown/binding-openharmony-arm64@1.2.1'
  - '@rolldown/binding-wasm32-wasi@1.2.1'
  - '@rolldown/binding-win32-arm64-msvc@1.2.1'
  - '@rolldown/binding-win32-x64-msvc@1.2.1'
  - '@vitejs/devtools-kit@0.4.10'
  - '@vitejs/devtools@0.4.10'
  - devframe@0.7.15
  - rolldown@1.2.1
  - strip-literal@4.0.0
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': ^9.2.0
    '@types/estree': ^1.0.9
    '@types/node': ^26.1.2
    '@types/picomatch': ^4.0.3
    '@vitest/coverage-v8': ^4.1.10
    bumpp: ^12.1.1
    chokidar: ^5.0.0
    eslint: ^10.8.0
    typescript: ^7.0.2
    unbuild: ^3.6.1
    vue-tsc: ^3.3.8
  playground:
    '@vitejs/devtools': ^0.4.10
    '@vitejs/plugin-vue': ^6.0.8
    vite: ^8.1.5
    vite-plugin-inspect: ^12.0.2
    vue: ^3.5.40
  prod:
    acorn: ^8.18.0
    escape-string-regexp: ^5.0.0
    estree-walker: ^3.0.3
    local-pkg: ^1.2.1
    magic-string: ^1.1.0
    mlly: ^1.8.2
    oxc-parser: ^0.142.0
    pathe: ^2.0.3
    picomatch: ^4.0.5
    pkg-types: ^2.3.1
    rolldown: ^1.2.1
    scule: ^1.3.0
    strip-literal: ^4.0.0
    tinyglobby: ^0.2.17
    unplugin: ^3.3.0
    unplugin-utils: ^0.3.2
  test:
    h3: ^1.15.11
    jquery: ^4.0.0
    lit: ^3.3.3
    vitest: ^4.1.10
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
allowBuilds:
  esbuild: true
