packages:
  - playground
catalog:
  '@antfu/eslint-config': ^3.10.0
  '@rollup/pluginutils': ^5.1.3
  '@types/estree': ^1.0.6
  '@types/node': ^22.10.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitest/coverage-v8': ^2.1.6
  acorn: ^8.14.0
  bumpp: ^9.8.1
  conventional-changelog-cli: ^5.0.0
  escape-string-regexp: ^5.0.0
  eslint: ^9.15.0
  estree-walker: ^3.0.3
  h3: ^1.13.0
  jquery: ^3.7.1
  lit: ^3.2.1
  local-pkg: ^0.5.1
  magic-string: ^0.30.14
  micromatch: ^4.0.8
  mlly: ^1.7.3
  pathe: ^1.1.2
  pkg-types: ^1.2.1
  scule: ^1.3.0
  strip-literal: ^2.1.1
  typescript: ~5.6.3
  unbuild: ^2.0.0
  unplugin: ^1.16.0
  vite: ^6.0.1
  vite-plugin-inspect: ^0.10.0
  vitest: ^2.1.6
  vue: ^3.5.13
  vue-tsc: ^2.1.10
