packages:
  - playground
catalogs:
  dev:
    '@antfu/eslint-config': ^4.14.1
    '@types/estree': ^1.0.8
    '@types/node': ^22.15.30
    '@types/picomatch': ^4.0.0
    '@vitest/coverage-v8': ^3.2.2
    bumpp: ^10.1.1
    conventional-changelog-cli: ^5.0.0
    eslint: ^9.28.0
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vue-tsc: ^2.2.10
  playground:
    '@vitejs/plugin-vue': ^5.2.4
    vite: ^6.3.5
    vite-plugin-inspect: ^11.1.0
    vue: ^3.5.16
  prod:
    acorn: ^8.14.1
    escape-string-regexp: ^5.0.0
    estree-walker: ^3.0.3
    local-pkg: ^1.1.1
    magic-string: ^0.30.17
    mlly: ^1.7.4
    pathe: ^2.0.3
    picomatch: ^4.0.2
    pkg-types: ^2.1.0
    scule: ^1.3.0
    strip-literal: ^3.0.0
    tinyglobby: ^0.2.14
    unplugin: ^2.3.5
    unplugin-utils: ^0.2.4
  test:
    h3: ^1.15.3
    jquery: ^3.7.1
    lit: ^3.3.0
    vitest: ^3.2.2
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
