packages:
  - playground
catalog:
  '@antfu/eslint-config': ^4.1.0
  '@rollup/pluginutils': ^5.1.4
  '@types/estree': ^1.0.6
  '@types/node': ^22.10.7
  '@types/picomatch': ^3.0.2
  '@vitejs/plugin-vue': ^5.2.1
  '@vitest/coverage-v8': ^3.0.3
  acorn: ^8.14.0
  bumpp: ^9.10.1
  conventional-changelog-cli: ^5.0.0
  escape-string-regexp: ^5.0.0
  eslint: ^9.18.0
  estree-walker: ^3.0.3
  fast-glob: ^3.3.3
  h3: ^1.13.1
  jquery: ^3.7.1
  lit: ^3.2.1
  local-pkg: ^1.0.0
  magic-string: ^0.30.17
  micromatch: ^4.0.8
  mlly: ^1.7.4
  pathe: ^2.0.2
  picomatch: ^4.0.2
  pkg-types: ^1.3.1
  scule: ^1.3.0
  strip-literal: ^3.0.0
  tinyglobby: ^0.2.10
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unplugin: ^2.1.2
  vite: ^6.0.11
  vite-plugin-inspect: ^10.1.0
  vitest: ^3.0.3
  vue: ^3.5.13
  vue-tsc: ^2.2.0
