export {}
declare global {
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onMounted: typeof import('vue')['onMounted']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const useAttrs: typeof import('vue')['useAttrs']
  const useSlots: typeof import('vue')['useSlots']
  const computed: typeof import('vue')['computed']
  const customRef: typeof import('vue')['customRef']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const markRaw: typeof import('vue')['markRaw']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const triggerRef: typeof import('vue')['triggerRef']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const unref: typeof import('vue')['unref']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const nextTick: typeof import('vue')['nextTick']
  const provide: typeof import('vue')['provide']
  const useCssModule: typeof import('vue')['useCssModule']
  const createApp: typeof import('vue')['createApp']
  const effectScope: typeof import('vue')['effectScope']
  const EffectScope: typeof import('vue')['EffectScope']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const useCssVars: typeof import('vue')['useCssVars']
  const multiplier: typeof import('/Users/antfu/i/unimport/playground/composables/index')['multiplier']
  const useDoubled: typeof import('/Users/antfu/i/unimport/playground/composables/index')['useDoubled']
  const bump: typeof import('/Users/antfu/i/unimport/playground/composables/index')['bump']
}
// for vue template auto import
declare module 'vue' {
  interface ComponentCustomProperties {
    onActivated: typeof import('vue')['onActivated']
    onBeforeMount: typeof import('vue')['onBeforeMount']
    onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
    onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
    onErrorCaptured: typeof import('vue')['onErrorCaptured']
    onDeactivated: typeof import('vue')['onDeactivated']
    onMounted: typeof import('vue')['onMounted']
    onServerPrefetch: typeof import('vue')['onServerPrefetch']
    onUnmounted: typeof import('vue')['onUnmounted']
    onUpdated: typeof import('vue')['onUpdated']
    useAttrs: typeof import('vue')['useAttrs']
    useSlots: typeof import('vue')['useSlots']
    computed: typeof import('vue')['computed']
    customRef: typeof import('vue')['customRef']
    isReadonly: typeof import('vue')['isReadonly']
    isRef: typeof import('vue')['isRef']
    markRaw: typeof import('vue')['markRaw']
    reactive: typeof import('vue')['reactive']
    readonly: typeof import('vue')['readonly']
    ref: typeof import('vue')['ref']
    shallowReactive: typeof import('vue')['shallowReactive']
    shallowReadonly: typeof import('vue')['shallowReadonly']
    shallowRef: typeof import('vue')['shallowRef']
    triggerRef: typeof import('vue')['triggerRef']
    toRaw: typeof import('vue')['toRaw']
    toRef: typeof import('vue')['toRef']
    toRefs: typeof import('vue')['toRefs']
    unref: typeof import('vue')['unref']
    watch: typeof import('vue')['watch']
    watchEffect: typeof import('vue')['watchEffect']
    defineComponent: typeof import('vue')['defineComponent']
    defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
    getCurrentInstance: typeof import('vue')['getCurrentInstance']
    h: typeof import('vue')['h']
    inject: typeof import('vue')['inject']
    nextTick: typeof import('vue')['nextTick']
    provide: typeof import('vue')['provide']
    useCssModule: typeof import('vue')['useCssModule']
    createApp: typeof import('vue')['createApp']
    effectScope: typeof import('vue')['effectScope']
    EffectScope: typeof import('vue')['EffectScope']
    getCurrentScope: typeof import('vue')['getCurrentScope']
    onScopeDispose: typeof import('vue')['onScopeDispose']
    onRenderTracked: typeof import('vue')['onRenderTracked']
    onRenderTriggered: typeof import('vue')['onRenderTriggered']
    resolveComponent: typeof import('vue')['resolveComponent']
    useCssVars: typeof import('vue')['useCssVars']
    multiplier: typeof import('/Users/antfu/i/unimport/playground/composables/index')['multiplier']
    useDoubled: typeof import('/Users/antfu/i/unimport/playground/composables/index')['useDoubled']
    bump: typeof import('/Users/antfu/i/unimport/playground/composables/index')['bump']
  }
}
