name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: sxzz/workflows/.github/workflows/release.yml@ea00b206fd53ae8f6d75c72fb1f67b8673ab8959 # main
    with:
      publish: true
    permissions:
      contents: write
      id-token: write
